import { Lato, Montserrat, Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import Footer from './components/Footer'

const Lato_init = Lato({
  subsets: ['latin'],
  weight: ['100', '400', '900'],
  variable: '--font-lato',
});

const Montserrat_init = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '600', '900'],
  variable: '--font-montserrat',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Michael Anderson',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
